### ISSUE TITLE
missing packatge Contoso.FaceSentimentAnalyzer_CS

### ISSUE THREAD

**Issue by conzog** [microsoft/WindowsVisionSkillsPreview#48]
I searched several nuget sources, I did find three Windows.AI.Vision,xxx packages, but not the FaceSentimentAnalyzer. Is this sample still in development? 

I see there is a similar sample Emoji8, I'll give that a try. This is for the Hackathon, so its not super critical … but it would be cool :)

https://github.com/Microsoft/Windows-Machine-Learning/tree/master/Samples/Emoji8/UWP/cs

Thanks, Conzog

**Comment by LPBourret** [comment]
Hi,
the NuGet packages for skills currently released are named with the prefix **Microsoft**.AI.Skills.xxx ([see nuget.org here](https://www.nuget.org/packages?q=Microsoft.AI.Skills)). 

The SentimentAnalzer skill sample is meant to teach skill developers how to write their own skills following the same design patterns and interfaces. You can build this sample skill yourself and produce a NuGet package to use locally following the [short series of steps here](https://www.nuget.org/packages?q=Microsoft.AI.Skills) and use it per the sample applications also shared on this repo 
- for C# usage [open the .sln solution file here](https://github.com/microsoft/WindowsVisionSkillsPreview/tree/master/samples/SentimentAnalyzerCustomSkill/cs) for UWP sample app
- for C++ Desktop and .NetCore 3.0 samples [open the solution file here](https://github.com/microsoft/WindowsVisionSkillsPreview/tree/master/samples/SentimentAnalyzerCustomSkill/cpp)
Note that as opposed to the Emoji8 Windows ML sample, this encompasses all the required assets (model file) and logic (preo-processing and post-processing) to be used in your app via the skill interface. 

If you think it would be useful for us to publish this sample skill alongside the other released one we can certainly consider doing so for ease of use. Have a good Hackathon! :)

**Comment by LPBourret** [comment]
closing for now

**Comment by conzog** [comment]
I got it working last weekend. I had to install the latest Windows Preview builds and update the correct SDKS. I set my one computer to get monthly previews and one to the self host so that I always get the latest. I'll keep an eye on to make sure I set it up correctly and my dev machine does not go out of date. 

 I'm unblocked to work on my solutions now, very happy customer :)

Thanks LP!
Conan

**Comment by conzog** [comment]
Oh yea, I had the Vision Skills drop from around May-June, but I found a newer drop (around  7/10), so I installed that one. That's when everything broke it was build against the latest drop of windows that just came out. So that was my lesson, have the insider program keep your computer up to date, and use two computers for slow and fast rings.

**Comment by LPBourret** [comment]
Just for reference, all versions of [Microsoft.AI.Skills.SkillInterfacePreview](https://www.nuget.org/packages/Microsoft.AI.Skills.SkillInterfacePreview/) and other skills that depend on it should work with UWP apps on Windows version 17763 (1809) and above, while for Win32 Desktop and .Net Core 3.0 apps ingesting Windows Vision Skills, Windows 18362 (1903) and above is required (since the SxS app manifest mechanism used requires it). Make sure however that you use the related version of Microsoft.AI.Skills.SkillInterfacePreview that your skill depend on (i.e. using Microsoft.AI.Skills.Vision.ObjectDetectorPreview version 0.1.0.2 depends on Microsoft.AI.Skills.SkillInterfacePreview version 0.5.2.15)
