### ISSUE TITLE
Crushing after deploying on windows IOT

### ISSUE THREAD

**Issue by ZubSam** [microsoft/WindowsVisionSkillsPreview#51]
We have UWP application.

After adding this libs from NuGet we have a problem.

When we try to run our application in desktop (**x86/64**) - all works.

But when we try to run into **rasbery pi 3 (windows IoT, ARM)** we have an exception when we try to initailize class ObjectDetectorDescriptor

> HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)

for example: 
`var descriptor = new ObjectDetectorDescriptor();`

**Comment by LPBourret** [comment]
Hi,
The ObjectDetector skill is supported for x64 only for now. We made this decision because the algorithm and machine learning model used under the hood take a lot of memory at runtime, beyond what 32-bit UWP appx permits, leading to OutOfMemory exceptions. We constrained it to x64 only until we can figure a way to gracefully scale to other architectures. That said, note that we could support other architectures for non-UWP apps not constrained with a maximum memory consumption amount. We are also tinkering with lighter and faster (though less precise) models, let us know if this is something you think we should prioritize.

**Comment by ZubSam** [comment]
Hello.
Thanks for the reply, in my opinion it is very important.
I think we are not the first to encounter such a problem, and in the future it will be very critical because of the growing demand for the rasbery/windows iot/uwp stack.
We would be very grateful if you can solve this problem as soon as possible.

**Comment by LPBourret** [comment]
Thank you for the feedback, closing this issue now, we will try to prioritize accordingly :)
